In [1]:
!pip install d2l==0.17.2

     |████████████████████████████████| 82 kB 612 kB/s 
     |████████████████████████████████| 11.6 MB 17.7 MB/s 
     |████████████████████████████████| 20.1 MB 80.6 MB/s 
     |████████████████████████████████| 61 kB 7.1 MB/s 
     |████████████████████████████████| 9.9 MB 53.1 MB/s 
  Attempting uninstall: numpy
    Found existing installation: numpy 1.19.5
    Uninstalling numpy-1.19.5:
      Successfully uninstalled numpy-1.19.5
  Attempting uninstall: requests
    Found existing installation: requests 2.23.0
    Uninstalling requests-2.23.0:
      Successfully uninstalled requests-2.23.0
  Attempting uninstall: pandas
    Found existing installation: pandas 1.1.5
    Uninstalling pandas-1.1.5:
      Successfully uninstalled pandas-1.1.5
  Attempting uninstall: matplotlib
    Found existing installation: matplotlib 3.2.2
    Uninstalling matplotlib-3.2.2:
      Successfully uninstalled matplotlib-3.2.2
ERROR: pip's dependency resolver does not currently take into account all the 

In [2]:
# Generating the Dataset
import numpy as np
import tensorflow as tf
from d2l import tensorflow as d2l

true_w = tf.constant([2, -3.4])
true_b = 4.2
features, labels = d2l.synthetic_data(true_w, true_b, 1000)

In [3]:
# Read the Dataset
def load_array(data_arrays, batch_size, is_train=True):
    """Construct a TensorFlow data iterator."""
    dataset = tf.data.Dataset.from_tensor_slices(data_arrays)
    if is_train:
        dataset = dataset.shuffle(buffer_size=1000)
    dataset = dataset.batch(batch_size)
    return dataset

batch_size = 10
data_iter = load_array((features, labels), batch_size)

In [4]:
next(iter(data_iter))

(<tf.Tensor: shape=(10, 2), dtype=float32, numpy=
 array([[ 1.688669  ,  0.72545063],
        [-0.5249305 ,  0.88893265],
        [-0.32319248,  1.3498088 ],
        [ 1.0819163 ,  0.5064121 ],
        [-0.6497484 , -0.3639561 ],
        [-2.0553129 ,  1.3941854 ],
        [ 1.1543156 , -0.6910725 ],
        [-1.3665886 , -0.11293046],
        [ 1.3778025 ,  0.6564738 ],
        [-0.5588872 ,  1.6793497 ]], dtype=float32)>,
 <tf.Tensor: shape=(10, 1), dtype=float32, numpy=
 array([[ 5.115118  ],
        [ 0.12998399],
        [-1.04327   ],
        [ 4.628033  ],
        [ 4.14389   ],
        [-4.6418777 ],
        [ 8.871196  ],
        [ 1.8362218 ],
        [ 4.722611  ],
        [-2.6298761 ]], dtype=float32)>)

In [5]:
# Defining the Model
# `keras` is the high-level API for TensorFlow
net = tf.keras.Sequential()
net.add(tf.keras.layers.Dense(1))

In [6]:
# Initializing Model Parameters
initializer = tf.initializers.RandomNormal(stddev=0.01)
net = tf.keras.Sequential()
net.add(tf.keras.layers.Dense(1, kernel_initializer=initializer))

In [7]:
# Defining the Loss Function
loss = tf.keras.losses.MeanSquaredError()

In [8]:
# Defining the Optimization Algorithm
trainer = tf.keras.optimizers.SGD(learning_rate=0.03)

In [9]:
# Training
num_epochs = 3
for epoch in range(num_epochs):
    for X, y in data_iter:
        with tf.GradientTape() as tape:
            l = loss(net(X, training=True), y)
        grads = tape.gradient(l, net.trainable_variables)
        trainer.apply_gradients(zip(grads, net.trainable_variables))
    l = loss(net(features), labels)
    print(f'epoch {epoch + 1}, loss {l:f}')

epoch 1, loss 0.000233
epoch 2, loss 0.000097
epoch 3, loss 0.000097


In [10]:
w = net.get_weights()[0]
print('error in estimating w', true_w - tf.reshape(w, true_w.shape))
b = net.get_weights()[1]
print('error in estimating b', true_b - b)

error in estimating w tf.Tensor([0.00029171 0.0004971 ], shape=(2,), dtype=float32)
error in estimating b [0.00082588]
